[package]
name = "ocelotter_runtime"
version = "0.1.0"
authors = ["Ben Evans <benjamin.john.evans@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.2.7"
lazy_static = "1.2.0"
regex = "1"
ocelotter_util = {path = "../util"}
parking_lot = "0.9"